version: '3.6'
services:
  nginx-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - network_base
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./certs:/etc/ssl   
networks:
  network_base: