version: '3.6'

networks:
  proxy_network:
    external: true  # Referência a uma rede externa existente

volumes:
  static-ficha:
    external: true  # Referência a uma rede externa existente

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl
      - static-ficha:/etc/nginx/static
